# Generated by Django 4.2.4 on 2023-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Webinar', 'Webinar'), ('Workshop', 'Workshop'), ('Conference', 'Conference'), ('Meetup', 'Meetup')], default='Webinar', max_length=50)),
                ('event_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
