# Generated by Django 4.2.4 on 2023-09-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.course')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='participants.participant')),
            ],
        ),
    ]
