# Generated by Django 4.2.4 on 2023-09-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('masterclasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterclassParticipant',
            fields=[
                ('masterclass_participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Registered', max_length=20)),
                ('registration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='masterclasses.masterclass')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterclasses', to='participants.participant')),
            ],
        ),
    ]
