# Generated by Django 4.2.4 on 2023-09-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Active', max_length=50)),
                ('enrollment_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='participants.participant')),
            ],
        ),
    ]
