# Generated by Django 4.2.4 on 2023-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('current_institution', models.CharField(max_length=255)),
                ('institutional_location', models.CharField(max_length=255)),
                ('institutional_address', models.TextField()),
                ('academic_status', models.CharField(choices=[('Graduate', 'Graduate'), ('Doctoral Researcher', 'Doctoral Researcher'), ('Post Doctoral Researcher', 'Post Doctoral Researcher'), ('Lecturer', 'Lecturer'), ('Independent Researcher/Scholar', 'Independent Researcher/Scholar'), ('Not Applicable', 'Not Applicable')], max_length=50)),
                ('faculty', models.CharField(choices=[('Natural Sciences', 'Natural Sciences'), ('Social Sciences', 'Social Sciences'), ('Management Sciences', 'Management Sciences'), ('Engineering/Technology', 'Engineering/Technology'), ('Medical/Clinical Sciences', 'Medical/Clinical Sciences'), ('Education', 'Education'), ('Humanities', 'Humanities'), ('Multidisciplinary', 'Multidisciplinary'), ('Not Applicable', 'Not Applicable')], max_length=50)),
                ('academic_biography', models.TextField()),
                ('previous_digital_skills', models.TextField()),
                ('github_account', models.URLField(blank=True, null=True)),
                ('linkedin_account', models.URLField(blank=True, null=True)),
                ('programming_languages', models.TextField(blank=True, null=True)),
                ('markup_languages', models.TextField(blank=True, null=True)),
                ('research_area', models.TextField(blank=True, null=True)),
                ('area_of_specialization', models.TextField(blank=True, null=True)),
                ('research_interests', models.TextField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
            options={
                'db_table': 'Participants',
            },
        ),
    ]
