# Generated by Django 4.2.4 on 2023-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('masterclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('masterclass_name', models.CharField(max_length=255)),
                ('masterclass_type', models.CharField(choices=[('Webinar', 'Webinar'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar')], default='Webinar', max_length=50)),
                ('masterclass_status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=50)),
                ('masterclass_date', models.DateTimeField()),
                ('masterclass_end_date', models.DateTimeField(blank=True, null=True)),
                ('masterclass_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
